safe: true
lsi: false
pygments: true
toplinks:
    - url: http://serialseb.com
      title: SerialSeb
    - url: http://openrasta.org
      title: OpenRasta
    - url: http://openwrap.org
      title: OpenWrap
leftlinks:
    - url: /index.html
      title: Home
    - url: http://codebetter.com/sebastienlambla/
      title: Blog
    - url: /bio/index.html
      title: Bio
    - url: /rest.html
      title: Practical Rest
    - url: /speaker/
      title: Talks
    - url: /testimonials.html
      title: Testimonials
